# Generated by Django 4.2.1 on 2023-08-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionnaire', '0002_rename_grade_user_personne_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceengin',
            name='motif_maint',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
