# Generated by Django 4.2.1 on 2023-08-16 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionnaire', '0003_alter_maintenanceengin_motif_maint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fournisseur', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=100)),
                ('description_fournisseur', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='engin',
            name='fournisseur_engin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionnaire.fournisseur'),
        ),
        migrations.AddField(
            model_name='ravitaillementcarburant',
            name='fournisseur_carburant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionnaire.fournisseur'),
        ),
        migrations.AddField(
            model_name='typemaintenance',
            name='fournisseur_maint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionnaire.fournisseur'),
        ),
    ]
