# Generated by Django 4.2.1 on 2023-08-16 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionnaire', '0004_fournisseur_engin_fournisseur_engin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typemaintenance',
            name='fournisseur_maint',
        ),
        migrations.AddField(
            model_name='maintenanceengin',
            name='fournisseur_maint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionnaire.fournisseur'),
        ),
    ]
