# Generated by Django 4.2.1 on 2023-08-16 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionnaire', '0005_remove_typemaintenance_fournisseur_maint_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtatEngin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_etat', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='engin',
            name='etat_engin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionnaire.etatengin'),
        ),
    ]
