# Generated by Django 4.2.1 on 2023-08-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionnaire', '0006_etatengin_engin_etat_engin'),
    ]

    operations = [
        migrations.AddField(
            model_name='ravitaillementcarburant',
            name='plein',
            field=models.BooleanField(default=False),
        ),
    ]
