# Generated by Django 4.2.1 on 2023-08-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionnaire', '0007_ravitaillementcarburant_plein'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribution',
            name='date_attribution',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='maintenanceengin',
            name='date_maint',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ravitaillementcarburant',
            name='date_rav',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='relevedistance',
            name='date_releve',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vidangeengin',
            name='date_vid',
            field=models.DateField(auto_now_add=True),
        ),
    ]
