# Generated by Django 4.2.1 on 2023-08-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionnaire', '0009_engin_date_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='engin',
            name='est_obsolete',
            field=models.BooleanField(default=False),
        ),
    ]
