# Generated by Django 4.2.1 on 2023-09-07 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionnaire', '0013_relevedistance_distance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vidangeengin',
            name='id',
        ),
        migrations.AddField(
            model_name='vidangeengin',
            name='maint_vid',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='gestionnaire.maintenanceengin'),
        ),
    ]
