# Generated by Django 4.2.1 on 2023-09-26 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionnaire', '0014_remove_vidangeengin_id_vidangeengin_maint_vid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personne',
            name='user',
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=15)),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionnaire.personne')),
            ],
        ),
    ]
