# Generated by Django 4.2.1 on 2023-10-05 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionnaire', '0020_remove_vidangeengin_maint_vid_vidangeengin_km_vid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceengin',
            name='Km_vid',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='VidangeEngin',
        ),
    ]
