# Generated by Django 4.2.1 on 2023-10-08 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionnaire', '0021_maintenanceengin_km_vid_delete_vidangeengin'),
    ]

    operations = [
        migrations.AddField(
            model_name='relevedistance',
            name='carb_consomme',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='relevedistance',
            name='carb_depart',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='relevedistance',
            name='carb_restant',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='relevedistance',
            name='date2_rav',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='relevedistance',
            name='mode_4x4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relevedistance',
            name='qte_rav',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='relevedistance',
            name='ravitaillement',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='T_Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emploie', models.DateField(auto_now_add=True)),
                ('solde', models.FloatField(default=0.0)),
                ('type_engin', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestionnaire.typeengin')),
            ],
        ),
    ]
