# Generated by Django 4.2.1 on 2023-10-08 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionnaire', '0022_relevedistance_carb_consomme_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_card',
            old_name='type_engin',
            new_name='type_engin_tcard',
        ),
    ]
