# Generated by Django 4.2.1 on 2023-10-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionnaire', '0023_rename_type_engin_t_card_type_engin_tcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='ravitaillementcarburant',
            name='Km_plein',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='ravitaillementcarburant',
            name='conso',
            field=models.FloatField(null=True),
        ),
    ]
