# Generated by Django 4.2.1 on 2023-10-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionnaire', '0026_chatbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='ravitaillementcarburant',
            name='carb_dispo',
            field=models.FloatField(null=True),
        ),
    ]
