# Generated by Django 4.2.1 on 2023-10-11 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionnaire', '0027_ravitaillementcarburant_carb_dispo'),
    ]

    operations = [
        migrations.AddField(
            model_name='engin',
            name='nja',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
