# Generated by Django 4.2.1 on 2023-10-11 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionnaire', '0028_engin_nja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ravitaillementcarburant',
            name='quantite_rav',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='relevedistance',
            name='carb_consomme',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='relevedistance',
            name='carb_depart',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='relevedistance',
            name='carb_restant',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='relevedistance',
            name='distance',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='relevedistance',
            name='mode_4x4',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='relevedistance',
            name='nbKmDebut',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='relevedistance',
            name='nbKmFin',
            field=models.FloatField(null=True),
        ),
    ]
