# Generated by Django 4.2.1 on 2023-10-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionnaire', '0029_alter_ravitaillementcarburant_quantite_rav_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='engin',
            name='vik',
            field=models.FloatField(null=True),
        ),
    ]
