# Generated by Django 4.2.1 on 2023-10-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionnaire', '0031_engin_capa_reserv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='engin',
            name='has_notification',
            field=models.BooleanField(default=False),
        ),
    ]
