# Generated by Django 4.2.1 on 2023-10-23 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionnaire', '0032_engin_has_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceengin',
            name='type_maint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionnaire.typemaintenance'),
        ),
    ]
