# Generated by Django 4.2.1 on 2023-10-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionnaire', '0033_alter_maintenanceengin_type_maint'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_card',
            name='approvisionnement',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
